- app/models/application_record.rb
- app/models/award.rb
- app/models/badge.rb
- app/models/badge_map.rb
- app/models/challenge.rb
- app/models/challenge_entry.rb
- app/models/participation.rb
- app/models/submission.rb
- app/models/user.rb
- db/migrate/20180131022405_add_columns_to_user.rb
- db/migrate/20180131025235_create_badges.rb
- db/migrate/20180131032835_create_awards.rb
- db/migrate/20180131034646_add_index_to_users_name.rb
- db/migrate/20180131034832_add_index_to_badges_name.rb
- db/migrate/20180131035248_create_submissions.rb
- db/migrate/20180131044112_create_badge_maps.rb
- db/migrate/20180131044430_create_challenges.rb
- db/migrate/20180131050445_create_participations.rb
- db/migrate/20180131051723_create_challenge_entries.rb
- db/schema.rb
- test/integration/user_signup_test.rb
- test/models/award_test.rb
- test/models/badge_map_test.rb
- test/models/badge_test.rb
- test/models/challenge_entry_test.rb
- test/models/challenge_test.rb
- test/models/participation_test.rb
- test/models/submission_test.rb
- test/models/user_test.rb
Here we go! Underlying data model time!
> Database model setup

- config/environments/production.rb
Reverts LastArtistStanding/last-artist-standing#11
> Revert "Update production.rb"

- app/controllers/submissions_controller.rb
- app/views/submissions/_form.html.erb
- app/views/submissions/show.html.erb
> CRITICAL: You will now be able to submit to custom challenges once they begin.
> IMPORTANT: When viewing a submission, you will be able to see what challenges it was submitted to.
> Added some clarifying guidelines to the submission page indicating what should be submitted.
> Submit to challenges implemented

- app/controllers/submissions_controller.rb
- app/views/submissions/_submission.json.jbuilder
Reverts LastArtistStanding/last-artist-standing#31, checking if build is fixed.
> Revert "submissions.json supports to & from params and returns limited user data"

- app/controllers/submissions_controller.rb
- app/views/submissions/_submission.json.jbuilder
Reverts LastArtistStanding/last-artist-standing#32
> Revert "Revert "submissions.json supports to & from params and returns limited user data""

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/views/layouts/_header.html.erb
- db/data/challenges.yaml
Removed turbolinks. Go fuck yourself, turbolinks.
Fixed javascript functionality carrying over to other pages.
Fixed lingering <br> tags in the DAD contest description.
Fixed the mobile collapse button not showing up clearly.
> Misc. hotfixes

- app/views/challenges/entries.html.erb
- app/views/layouts/_header.html.erb
Fixes the navbar not displacing page content and a challenge entry page name bug.
> navbar and name fix

- app/controllers/submissions_controller.rb
- app/models/challenge.rb
- app/models/site_status.rb
- app/views/submissions/_editform.html.erb
- app/views/submissions/_form.html.erb
- db/migrate/20190822045648_create_site_statuses.rb
- db/migrate/20190823051833_add_processed_to_participations.rb
- db/migrate/20190824204733_add_current_streak_to_users.rb
- db/schema.rb
- lib/tasks/dad_tasks.rake
- spec/models/site_status_spec.rb
sweet christ please don't break things horribly
> Rollover improvements

- app/assets/stylesheets/application.scss
- app/controllers/challenges_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/submissions_controller.rb
- app/models/submission.rb
- app/uploaders/image_uploader.rb
- app/views/challenges/entries.html.erb
- app/views/pages/home.html.erb
- app/views/submissions/index.html.erb
- app/views/submissions/show.html.erb
- app/views/users/show.html.erb
- app/views/users/submissions.html.erb
Reverts LastArtistStanding/last-artist-standing#61
> Revert "User experience bonuses."

- .gitignore
- Gemfile
- Gemfile.lock
- app/assets/config/manifest.js
- app/assets/javascripts/application.js
- config/application.rb
- db/migrate/20180117222023_create_users.rb
- lib/tasks/dad_tasks.rake
> Gem update

- README.md
Merging this PR should be deferred until we solve the remaining issues that exist in my development environment, in case further explanation is necessary.
> Updated the README to explain the new way to set up the dev environment.

- README.md
This PR only affects the README, so I don't expect you will have any issues with merging it. You may either merge this PR immediately, or wait as described by my comment in #87. Any of the orders I described work equally well for me.
> Improve the README: easier setup method, syntax highlighting.

- app/controllers/challenges_controller.rb
- app/controllers/users_controller.rb
- app/views/challenges/entries.html.slim
- app/views/users/index.html.slim
- app/views/users/submissions.html.slim
Add a pagination under the submissions to change page when we are at the bottom of the pages :
- /challenges/:id/entries
- /users
- /users/:id/submissions
> Pagination on users and submissions

- app/helpers/submissions_helper.rb
- app/views/challenges/entries.html.slim
- app/views/submissions/index.html.slim
- app/views/users/submissions.html.slim
**New modal when clicking a card on the following pages :**
- /users/:id/submissions
- /challenges/:id/entries
- /submissions
**The modal contains :**
- "Details" button link to "/submissions/:id"
- "Full size" button open a new tab with the image link
**Preview :**
> New modals

- app/controllers/challenges_controller.rb
- app/controllers/pages_controller.rb
- app/views/challenges/index.html.slim
- app/views/challenges/show.html.slim
- app/views/pages/home.html.erb
Filtered submissions that are unapproved or soft-deleted
Filtered out comments that are made on submissions.nsfw_level > current_user.nsfw_level
Filtered out challenges that are soft_deleted or challenges.nsfw_level > current_user.nsfw_level
Some code refactoring to please rubocop.
> Filter out unapproved, soft deleted, and nsfw content (based on user defined level) from home page

- app/controllers/pages_controller.rb
> Fixed error that messed up urls from the feed

- app/views/challenges/entries.html.slim
- app/views/submissions/index.html.slim
- app/views/users/submissions.html.slim
- When image is small, the modal width fit it ( exept images < 150px because the buttons look bad)
- When opening and closing different submissions the modal should wait until the image is loaded to open
> better modal for small images

- app/assets/stylesheets/application.scss
- app/views/challenges/entries.html.slim
- app/views/submissions/index.html.slim
- app/views/users/submissions.html.slim
- Loading when image is loading
- link to submission if javascript no active
- smaller modal size
> modal improvement from feedback

- app/controllers/submissions_controller.rb
Fixed issue where scores were not being updated correctly.
> fixed issue where house score is incorrectly updated

- app/controllers/followers_controller.rb
Made a check to prevent users from following themselves.
> Cannot follow yourself

- app/assets/stylesheets/application.scss
- app/controllers/submissions_controller.rb
- app/controllers/users_controller.rb
- app/models/house.rb
- app/views/application/_usercard.html.slim
- app/views/submissions/show.html.slim
- app/views/users/index.html.slim
- app/views/users/show.html.slim
- db/schema.rb
Initialize staging, show house on usercard.
> Show house on usercard.

- app/controllers/application_controller.rb
- app/controllers/comments_controller.rb
- app/controllers/discussions_controller.rb
- app/controllers/forums_controller.rb
- app/models/board.rb
- app/models/comment.rb
- app/models/discussion.rb
- app/models/user.rb
- app/views/discussions/_form.html.slim
- app/views/discussions/index.html.slim
- app/views/discussions/new.html.slim
- app/views/discussions/show.html.slim
- app/views/forums/index.html.slim
- app/views/layouts/_header.html.slim
- config/routes.rb
- db/migrate/20201203024448_create_discussions.rb
- db/migrate/20201203032626_create_boards.rb
- db/migrate/20201203033417_add_board_to_discussion.rb
- db/schema.rb
- spec/models/board_spec.rb
- spec/models/discussion_spec.rb
Currently completed:
- Board, Discussion models
- Comments expanded to facilitate discussions
- Comment permissions apply to Discussion Comments
- Site Bans Prevent Comment Posting/Deleting
- Basic Navigation
- Dynamic Routing
- Threads Sorted By Latest Post
- Functional Board Permission Levels (Who can make threads?)
Needs to be Worked:
- Moderator options to lock, pin and soft delete Discussions
- Piece out comments into a partial
- Eliminate the extremely bad N+1 on the Discussions Index
- Notifications
- Pagination on both Discussion List and Discussion View Page
- Markdown
- Anonymous Posting
- Report Function
- Etc
> Emergency Forums Implementation.

- Gemfile.lock
> Downgrade bundle to 2.1.4

- app/views/users/show.html.slim
Feature suggested in chat. Simple enough to implement. Merge at your leisure. Or don't.
> Adding the date the user joined to their profile.

- app/views/houses/index.html.slim
Fixed the HTML that resulted in the weird styling for deleted users.
> Fix House HTML for Deleted Users

- app/assets/stylesheets/application.scss
- app/models/comment.rb
also cleaned up rubocop in the models/comment.rb file.
> Fixed Markdown Quote Styling

- Gemfile.lock
- app/views/submissions/index.html.slim
- app/views/users/submissions.html.slim
Removed the javascript related to the click zoom feature.
Sorry 4v. It was kind of annoying.
> click zoom removed

- lib/tasks/dad_tasks.rake
Added some code to automatically approve users after they reach level 3.
Also removed a comma.
> adding auto approve

- app/assets/stylesheets/houses.scss
- app/controllers/houses_controller.rb
- app/views/houses/index.html.slim
Fixes Issue #246 
Unified the date selector. Shouldn't have any more weird behavior between buttons.
> Houses Date Selector is Borked

- app/controllers/pages_controller.rb
- app/views/application/_usercard.html.slim
- app/views/layouts/application.html.slim
- app/views/pages/home.html.erb
- app/views/submissions/show.html.slim
- app/views/users/show.html.slim
Adds functionality to allow sites to embed previews using links to dad.
> Adding Open Graph Previews to Dad

- app/helpers/markdown_helper.rb
Removed a piece of code that was adding double new lines and making bulleted lists look dumb.
> Removed new lines between bullet points

- app/views/submissions/show.html.slim
* Houses Date Selector is Borked (#247)
* Unified the date selector. Shouldn't have any more weird behavior.
* Fixed a broken test.
* Added some logic so users can't break the db query by messing with the day
Co-authored-by: nsix <nsix@cock.li>
* Quick fixes for crashes cause by challenges (#252)
* Stops seasonal challenges from breaking the homepage when they don't exist.
Also prevents the dad main challenge from breaking if the id should ever change.
* Reverted this fix for the main challenge. This will cause the site to break if the main challenge ever changes id.
Co-authored-by: nsix <nsix@cock.li>
* Fixed the issue, but bullet lists are still super spaced out. Not sure how to configure the markdown hellper to not do that. (#254)
Co-authored-by: nsix <nsix@cock.li>
* Adding Open Graph …
> trying desperately to resolve this shit (#259)
